### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mattbrailsford** [vendrcontrib/vendr-payment-provider-reepay#1]
Just to note a few things to resolve in this

- [x] Remove the init.ps1 and init.cmd files
- [x] Update `Build.Prepare.targets` with Flurl DLL dependencies (See https://github.com/vendrhub/vendr-payment-provider-paypal/blob/dev/build/Build.Prepare.targets#L13-L14)
- [x] Update NuSpec file to include Flurl dependencies (See https://github.com/vendrhub/vendr-payment-provider-paypal/blob/dev/build/NuSpecs/Vendr.PaymentProviders.PayPal.nuspec#L19-L20)
- [x] Update NuSpec files Author, Owners and Copyright as they won't be `Outfield Digital`
- [x] Rename provider to `ReepayCheckoutPaymentProvider` in preparation of integrating subscription payments into the same provider
- [x] Check `FetchPaymentStatus` on order
- [x] Test installing packages both by nuget and umbraco package file

**Comment by bjarnef** [comment]
@mattbrailsford maybe we should just change this to `ReepayCheckoutPaymentProvider` like you did with Stripe. This Reepay payment provider hasn't been released yet, so I think it shouldn't be neccesary to obsolete it 🙂

Do you have a suggestion for the Author and Owners for contrib payment providers? 🙂

**Comment by mattbrailsford** [comment]
If you intend to integrate subscription payments into it, then yea, go for it :+1:

**Comment by bjarnef** [comment]
Yeah, maybe not neccesary for initial release, but would be great if it was preparred to support recurring payment 👍

**Comment by bjarnef** [comment]
@mattbrailsford I have updated these todos and used `Vendr Contrib`. Maybe the payment provider should use these basics and start as a "Contrib" payment provider? https://github.com/vendrhub/vendr-payment-provider-template

Not sure if it is possible to move the template repository to `vendrcontrib` organisation while still restricting who can make changes to this repository.
